name: gat
model:
  _target_: src.models.gat.GATModel
  num_layers: 5
  num_features: null
  conv_hidden_dim: 64
  fc_hidden_dim: 128
  num_classes: null
  dropout: 0.5
  graph_pooling_type: ${agg}
  neighbor_pooling_type: ${agg}
  lr: 0.001