_target_: src.models.gin.GINModel
num_layers: ${num_layers}
num_mlp_layers: 2
num_features: null
hidden_dim: 64
num_classes: null
final_dropout: 0.5
train_eps: False
graph_pooling_type: ${agg}
neighbor_pooling_type: ${agg}
lr: ${lr}
