_target_: pytorch_lightning.Trainer
check_val_every_n_epoch: 1
log_every_n_steps: 5
accelerator: ${accelerator}
devices: ${devices}
max_epochs: 200
num_sanity_val_steps: 0
deterministic: false 
logger: ${logger}
